services:
  web:
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env.docker-compose

  postgres:
    image: postgres:16
    restart: always
    env_file:
      - .env.docker-compose
    ports:
      - "5432:5432"
    volumes:
      - postgres_productos:/var/lib/postgresql/data

volumes:
  postgres_productos: